server:
  port: 8765
spring:
  application:
    name: service-feign
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #开启断路器