server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否向eureka注册 本身是eureka不用注册
    fetchRegistry: false #是否向缓存中注册 eureka不需要注册
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  profiles:
#    active: peer1