server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huangdu94/down-to-earth.git
          search-paths: SpringCloud学习/code/respo
eureka:
  instance:
    prefer-ip-address: true
    # ip-address: 127.0.0.1 # 这一行配置可以去掉
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/