server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huangdu94/down-to-earth.git
          searchPaths: code/respo